```{r setup}
knitr::opts_knit$set(root.dir = '~/Desktop/bio_modelling_course/mod5/proj5/')
```

# Code for question 2

```{r}
library(tidyverse)
library(gridExtra)

bkv <- 0.02
bgv <- 0.30
bgc <- 0.32
fv <- 0.25
fc <- 0.07
la <- 0.05
lb <- 0.025
h1 <- 0.5
h4 <- 0.4

aV <- h1*bkv + h4*bgv
bV <- (fv + la)
aBC <- h4*bgc
bBC <- lb

g1 <- function(x) 1 - exp(-0.5*x)

f <- function(now) {
  dV <- aV - bV*now[1]
  dBC <- aBC - bBC*now[2] - fc*g1(now[2]/now[1])*now[2]
  c(dV,dBC)
}

find_equib <- function (init) {
  list(init, 
       nlm(function(now) sum(f(now)**2), init)$estimate)
}
equibs <- map(map(1:10, function(x) rnorm(2, sd = 10)**2),
              find_equib)

equibs
equib <- equibs[[1]][[2]]
equib

-(fv + la)
-fc/2*((equib[1]/equib[2])**2)*exp(equib[1]/equib[2])

euler_auton <- function(diff, x0,
                        n, h, improv = T,
                        names) {
  xs <- matrix(nrow = n, ncol = 2)
  xs[1,] <- x0
  for (i in 2:n) {
    xstar <- xs[i-1,] + diff(xs[i-1,])*h
    if (improv) {
      xs[i,] <- xs[i-1,] + (diff(xs[i-1,]) + diff(xstar))*h/2
    }
    else {   
      xs[i,] <- xstar
    }
  }
  colnames(xs) <- names
  data.frame(xs)
}

sim1 <- euler_auton(f, c(0.2, 0.4), 
                    1500, 1/24, T, c('V', 'BC'))
sim2 <- euler_auton(f, c(2, 0.1), 
                    1500, 1/24, T, c('V', 'BC'))
grid.arrange(grobs = list(sim1 %>% 
                            ggplot(aes(V, BC)) + 
                            geom_path() +
                            geom_point(aes(x = equib[1], y = equib[2]), color='green', size=3),
                          sim2 %>% 
                            ggplot(aes(V, BC)) + 
                            geom_path() +
                            geom_point(aes(x = equib[1], y = equib[2]), color='green', size=3)),
             nrow=1)
```

# Code for question 3

```{r}
setwd('~/Desktop/bio_modelling_course/mod5/proj5/')

library(tidyverse)
library(xtable)

a <- 2
b <- 0.001
c <- 0.1
d <- 0.01
e <- 0.2
f <- 0.7

Geq <- function(alpha, beta) {
  
  b_temp <- a*(1-b/beta)
  dis <- b_temp**2 + 4*a*alpha
  
  c(0, 
    1/alpha, 
    1/d,
    (b_temp + sqrt(dis))/(2*a*alpha),
    (b_temp - sqrt(dis))/(2*a*alpha))
}

Feq <- function(alpha, beta) {
  c(0, 
    0, 
    (d-alpha)/(d*b),
    1/beta,
    1/beta)
}

Ueq <- function(G4, G5) {
  c(0,
    0,
    0,
    (d*G4 - 1)/e,
    (d*G5 - 1)/e)
}

find_equibs <- function(alpha, beta) {
  Geqs <- Geq(alpha, beta)
  Feqs <- Feq(alpha, beta)
  Ueqs <- Ueq(Geqs[4], Geqs[5])
  eqs <- matrix(c(Geqs, Feqs, Ueqs),
                nrow = 5)
  colnames(eqs) <- c('G', 'F', 'U')
  rownames(eqs) <- c('L1', 'L2', 'L3', 'L4', 'L5')
  eqs
}

find_equibs(0.002, 0.005)
find_equibs(0.002, 0.0008)
find_equibs(0.02, 0.0008)
print(xtable(find_equibs(0.002, 0.005)), file='eq_t1.tex')
print(xtable(find_equibs(0.002, 0.0008)), file='eq_t2.tex')
print(xtable(find_equibs(0.02, 0.0008)), file='eq_t3.tex')

dF <- function(Geq,Feq,Ueq, alpha,beta) {
  matrix(c(a*(1-2*alpha*Geq-b*Feq),
           c*d*Feq,
           0,
           -a*b*Geq,
           c*(d*Geq-1-e*Ueq),
           -c*e*Feq,
           0,
           f*beta*Ueq,
           f*(beta*Feq - 1)),
         nrow=3
         )
}

L4 <- find_equibs(0.002, 0.005)[4,]
eigen(dF(L4[1], L4[2], L4[3], 0.002, 0.005))$values
```

